GET http://localhost:3333/getusers 

###
POST http://localhost:3330/user
Content-Type: application/json 
 { 
	  
      "name": "Aim Hemã de assis",
      "email": "Aim",
      "password": "*****" 

      
 }
